### ISSUE TITLE
Upgrade to Laravel 11

### ISSUE THREAD

**Issue by robert-abram** [lepikhinb/momentum-trail#21]

**Comment by bobbypiperagrovista** [comment]
There is an open PR https://github.com/lepikhinb/momentum-trail/pull/19 just waiting for it to be merged

**Comment by bobbypiper** [comment]
@robert-abram There is an open PR https://github.com/lepikhinb/momentum-trail/pull/19 just waiting for it to be merged.

**Comment by im-aeo** [comment]
I need this upgrade as every thing else is ready for laravel 11

**Comment by lepikhinb** [comment]
@im-aeo it's already been updated

**Comment by im-aeo** [comment]
> @im-aeo it's already been updated

I thought so. I was saying this because when I try to upgrade, it Throws an error for illuminate/support.

**Comment by lepikhinb** [comment]
@im-aeo Just installed it on a fresh Laravel 11. What does the output say?

**Comment by im-aeo** [comment]
> @im-aeo Just installed it on a fresh Laravel 11. What does the output say?

![image](https://github.com/lepikhinb/momentum-trail/assets/109118450/ec4bd933-d2a6-467d-ba60-6e8fc302c54f)

**Comment by im-aeo** [comment]
I assume i should upgrade both packages correct?

**Comment by im-aeo** [comment]
fixed.

**Comment by im-aeo** [comment]
thank you @lepikhinb
