### ISSUE TITLE
Route Params

### ISSUE THREAD

**Issue by SDIjeremy** [lepikhinb/momentum-trail#3]
The docs say refer to Ziggy docs, but many features are missing ...

Is there plan to add these missing features?

**Retrieving the current route params: `route().params`**

```js
// Route called 'events.venues.show', with URI '/events/{event}/venues/{venue}'
// Current window URL is https://myapp.com/events/1/venues/2?authors=all

route().params; // { event: '1', venue: '2', authors: 'all' }
```

**Comment by lepikhinb** [comment]
Yeah, going to work more on it in the coming week.

**Comment by jjjrmy** [comment]
bump

**Comment by lepikhinb** [comment]
You should be good with the recent version. Please try updating the package
